# Copy this file to config.yaml and fill in values.
google_sheets:
  spreadsheet_id: "YOUR_SHEET_ID"   # e.g., 1AbCd... from the URL
  worksheet_raw: "raw_candidates"
  worksheet_filtered: "filtered_candidates"
  service_account_json_env: "GOOGLE_CREDENTIALS_JSON"  # env var name holding the SA JSON

scraper:
  days_back: 7         # search window (since: today - days_back)
  max_per_query: 300   # soft cap per query (snscrape is unbounded; we'll stop early)

scoring:
  threshold: 70
  # keyword weights (regex; case-sensitive/off by default)
  weights:
    # Roles / functions (supply / acquisition)
    "(用地\s*仕入|仕入\s*営業|買取\s*再販|任意売却\s*営業|売買\s*仲介)": 40
    # Intent (career move / frustration)
    "(辞めたい|有給\s*消化|退職(代行)?|求職中|転職\s*活動中|次の仕事)": 25
    # Skill / license
    "(宅建|宅地建物取引士|査定|査定書|レインズ)": 20
    # Region (Kanto by default; customize)
    "(東京|神奈川|千葉|埼玉)": 10
    # Engagement
    "(いいね|RT|リツイート)": 5

filters:
  min_len: 10
  exclude_company_patterns: "(採用|求人|株式会社|Inc\.|会社|代理店|募集)"
