# Copy to config.yaml at runtime (workflow does this automatically)
google_sheets:
  spreadsheet_id: "YOUR_SHEET_ID"   # will be replaced by workflow
  worksheet_raw: "raw_candidates"
  worksheet_filtered: "filtered_candidates"
  service_account_json_env: "GOOGLE_CREDENTIALS_JSON"

scraper:
  days_back: 7
  max_per_query: 300

scoring:
  threshold: 70
  weights:
    '(用地\s*仕入|仕入\s*営業|買取\s*再販|任意売却\s*営業|売買\s*仲介)': 40
    '(辞めたい|有給\s*消化|退職(代行)?|求職中|転職\s*活動中|次の仕事)': 25
    '(宅建|宅地建物取引士|査定|査定書|レインズ)': 20
    '(東京|神奈川|千葉|埼玉)': 10
    '(いいね|RT|リツイート)': 5

filters:
  min_len: 10
  exclude_company_patterns: '(採用|求人|株式会社|Inc\.|会社|代理店|募集)'
